version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fluxocerto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./packages/backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/fluxocerto?schema=public"
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge